export const workshopInfo = [
  {
    date: "Friday, Febuary 3rd",
    events: [
      {
        title: "Team Mixer - Network with other hackers and form a team!",
        location: "Workshop A - Classroom 150",
        hostedBy: "CruzHacks - Mia",
        startTime: "9:15 pm",
        endTime: "10:00 pm",
      },
      {
        title: "Tips for First Hackathon",
        location: "Workshop B - Classroom 151",
        hostedBy: "ACM-W - Wendy Chen, Neeha Ravula, Tanisha Katoch",
        startTime: "9:15 pm",
        endTime: "10:00 pm",
      },
      {
        title: "Intro to Git",
        location: "Workshop C - Classroom 152",
        hostedBy: "Slugbotics - Ishan Madan",
        startTime: "9:15 pm",
        endTime: "10:00 pm",
      },
      {
        title: "Getting Started with Lightship",
        location: "Workshop A - Classroom 150",
        hostedBy: "Niantic - Gilberto Lopez Zayas",
        startTime: "10:00 pm",
        endTime: "11:00 pm",
      },
    ],
  },
  {
    date: "Saturday, February 4th",
    events: [
      {
        title: "Intro to Python",
        location: "Workshop A - Classroom 150",
        hostedBy: "Bioinformatics - Nitya Jain",
        startTime: "9:00 am",
        endTime: "10:00 am",
      },
      {
        title: "Resume/Cover Letter Workshop",
        location: "Workshop B - Classroom 151",
        hostedBy: "CruzHacks",
        startTime: "9:00 am",
        endTime: "10:00 am",
      },
      {
        title: "Intro to Figma",
        location: "Workshop B - Classroom 151",
        hostedBy: "DSC - Coen Adler, Arshad Mohammad, Anusha Pai",
        startTime: "10:00 am",
        endTime: "11:00 am",
      },
      {
        title: "Lightship VPS and Remote Content Authoring",
        location: "Workshop A - Classroom 150",
        hostedBy: "Niantic - Evie Powell",
        startTime: "11:00 am",
        endTime: "12:00 pm",
      },
      {
        title: "MLH Bob Ross MS Paint",
        location: "Workshop B - Classroom 151",
        hostedBy: "MLH - Mansi",
        startTime: "2:00 pm",
        endTime: "2:30 pm",
      },
      {
        title: "Intro to Algorithms and Applications",
        location: "Workshop A - Classroom 150",
        hostedBy: "Rocket Team - Aanand Kainth",
        startTime: "2:00 pm",
        endTime: "3:00 pm",
      },
      {
        title: "Intro to React",
        location: "Workshop A - Classroom 150",
        hostedBy: "Rocket Team - Aanand Kainth",
        startTime: "3:00 pm",
        endTime: "4:00 pm",
      },
      {
        title: "Cup Stacking Competition",
        location: "Workshop B - Classroom 151",
        hostedBy: "CruzHacks",
        startTime: "3:00 pm",
        endTime: "4:00 pm",
      },
      {
        title: "CruzHacks Organizer Interest Meeting",
        location: "Workshop C - Classroom 152",
        hostedBy: "CruzHacks",
        startTime: "4:00 pm",
        endTime: "4:30 pm",
      },

      {
        title: "Intro to UI",
        location: "Workshop A - Classroom 150",
        hostedBy: "CTD - Bianca Menor, Harshith Pothula, and Kayla Nguyen",
        startTime: "4:00 pm",
        endTime: "5:00 pm",
      },
      {
        title: "MLH Snyk Capture the Flag Cyber Security Challenge",
        location: "Workshop B - Classroom 151",
        hostedBy: "MLH - Mansi",
        startTime: "4:30 pm",
        endTime: "5:00 pm",
      },
      {
        title: "DevPost Q&A",
        location: "Workshop A - Classroom 150",
        hostedBy: "MLH - Mansi",
        startTime: "8:00 pm",
        endTime: "8:30",
      },
    ],
  },
]
