import React from "react"
import { Step } from "../../../utils/hackerapplication"

export const demographicSteps: Step[] = [
  // Step 1
  [
    [
      { text: "Demograhpic Information", type: "title" },
      <h2
        key={"demographic_note"}
        className='text-center text-xs md:w-2/3 md:text-sm'
      >
        The information collected here will be used for statistical purposes
        only. In accordance with the{" "}
        <a href='https://mlh.io/privacy' className='text-blue-button'>
          MLH Privacy Polich
        </a>
      </h2>,
    ],
    [
      { text: "What's your age?" },
      {
        inputType: "text",
        field: "age",
        additionalInputProps: {
          type: "number",
          placeholder: "How old are you?",
        },
      },
    ],
    [
      { text: "Where do you reside?" },
      // TODO: fetch country options from API
      { inputType: "combo", field: "country", options: ["USA", "Canada"] },
    ],
    [
      { text: "What school do you attend?" },
      { text: "Or most recently attended?" },
      // TODO: make combobox; fetch school options from API
      {
        inputType: "text",
        field: "school",
        additionalInputProps: { placeholder: "School name" },
      },
    ],
  ],

  // Step 2
  [
    [{ text: "UCSC College Affiliation" }],
    [
      {
        inputType: "radio",
        field: "ucsc_college_affiliation",
        options: [
          "Crown",
          "Merrill",
          "Cowell",
          "Stevenson",
          "Porter",
          "Kresge",
          "Oakes",
          "Rachel Carson",
          "College 9",
          "College 10",
          "Graduate Student",
          "N/A (I do not attend UCSC",
        ],
        arrange: "vertical-inline",
      },
    ],
  ],

  // Step 3
  [
    [{ text: "What year are in?" }],
    [
      {
        inputType: "radio",
        field: "year_in_school",
        options: [
          "HighSchool",
          "Freshman",
          "Sophomore",
          "Junior",
          "Senior",
          "Graduate Student",
        ],
      },
    ],
  ],

  // Step 4
  [
    [
      {
        text: "In what type of educational institution are you currently enrolled in?",
      },
    ],
    [
      {
        inputType: "radio",
        field: "education_level",
        options: [
          "Less than Secondary/High School",
          "Secondary/High School",
          "Undergarduate",
          "Graduate",
          "Code School/Bootcamp",
          "Other Vocational/Trade Program or Apprenticeship",
          "Not currently a student",
          "Prefer not to answer",
          "Other",
        ],
      },
    ],
  ],

  // Step 5
  [
    [
      { text: "What year will you graduate from your current school?" },
      {
        inputType: "radio",
        field: "graduation_year",
        options: ["2023", "2024", "2025", "2026", "2027", "2027 and beyond"],
      },
    ],
  ],

  // Step 6
  [
    [
      {
        text: "What is your major / area of Study? If you already graduated, what was your major/ primary area of study?",
      },
      {
        inputType: "combo",
        field: "area_of_study",
        // list of college majors
        options: [
          "Accounting",
          "Actuarial Science",
          "Advertising Major",
          "Aerospace Engineering",
          "African Languages, Literatures, and Linguistics",
          "African Studies",
          "African-American Studies",
          "Agricultural Business and Management",
          "Agricultural Economics",
          "Agricultural Education",
          "Agricultural Journalism",
          "Agricultural Mechanization Major",
          "Agricultural Technology Management",
          "Agricultural/Biological Engineering and Bioengineering",
          "Agriculture",
          "Agronomy and Crop Science",
          "Air Traffic Control",
          "American History",
          "American Literature",
          "American Sign Language",
          "American Studies",
          "Anatomy",
          "Ancient Studies",
          "Animal Behavior and Ethology",
          "Animal Science",
          "Animation and Special Effects",
          "Anthropology",
          "Applied Mathematics",
          "Aquaculture",
          "Aquatic Biology",
          "Arabic",
          "Archeology",
          "Architectural Engineering",
          "Architectural History",
          "Architecture",
          "Art",
          "Art Education",
          "Art History",
          "Art Therapy",
          "Artificial Intelligence and Robotics",
          "Asian-American Studies",
          "Astronomy",
          "Astrophysics",
          "Athletic Training",
          "Atmospheric Science",
          "Automotive Engineering",
          "Aviation",
          "Bakery Science",
          "Biblical Studies",
          "Biochemistry",
          "Bioethics",
          "Biology",
          "Biomedical Engineering",
          "Biomedical Science",
          "Biopsychology",
          "Biotechnology",
          "Botany/Plant Biology",
          "Business Administration/Management",
          "Business Communications",
          "Business Education",
          "Canadian Studies",
          "Caribbean Studies",
          "Cell Biology Major",
          "Ceramic Engineering",
          "Ceramics",
          "Chemical Engineering Major",
          "Chemical Physics",
          "Chemistry Major",
          "Child Care",
          "Child Development",
          "Chinese",
          "Chiropractic",
          "Church Music",
          "Cinematography and Film/Video Production",
          "Circulation Technology",
          "Civil Engineering",
          "Classics",
          "Clinical Psychology",
          "Cognitive Psychology",
          "Communication Disorders",
          "Communications Studies/Speech Communication and Rhetoric",
          "Comparative Literature",
          "Computer and Information Science",
          "Computer Engineering",
          "Computer Graphics",
          "Computer Systems Analysis Major",
          "Construction Management",
          "Counseling",
          "Crafts",
          "Creative Writing",
          "Criminal Science",
          "Criminology",
          "Culinary Arts",
          "Dance",
          "Data Processing",
          "Dental Hygiene",
          "Developmental Psychology",
          "Diagnostic Medical Sonography",
          "Dietetics",
          "Digital Communications and Media/Multimedia",
          "Drawing",
          "Early Childhood Education",
          "East Asian Studies",
          "East European Studies",
          "Ecology",
          "Economics Major",
          "Education",
          "Education Administration",
          "Education of the Deaf",
          "Educational Psychology",
          "Electrical Engineering",
          "Elementary Education",
          "Engineering Mechanics",
          "Engineering Physics",
          "English",
          "English Composition",
          "English Literature Major",
          "Entomology",
          "Entrepreneurship Major",
          "Environmental Design/Architecture",
          "Environmental Science",
          "Environmental/Environmental Health Engineering",
          "Epidemiology",
          "Equine Studies",
          "Ethnic Studies",
          "European History",
          "Experimental Pathology",
          "Experimental Psychology",
          "Fashion Design",
          "Fashion Merchandising",
          "Feed Science",
          "Fiber, Textiles, and Weaving Arts",
          "Film",
          "Finance",
          "Floriculture",
          "Food Science",
          "Forensic Science",
          "Forestry",
          "French",
          "Furniture Design",
          "Game Design",
          "Gay and Lesbian Studies",
          "Genetics",
          "Geography",
          "Geological Engineering",
          "Geology",
          "Geophysics",
          "German",
          "Gerontology",
          "Government Major",
          "Graphic Design",
          "Health Administration",
          "Hebrew",
          "Hispanic-American, Puerto Rican, and Chicano Studies",
          "Historic Preservation",
          "History",
          "Home Economics",
          "Horticulture",
          "Hospitality",
          "Human Development",
          "Human Resources Management Major",
          "Illustration",
          "Industrial Design",
          "Industrial Engineering",
          "Industrial Management",
          "Industrial Psychology",
          "Information Technology",
          "Interior Architecture",
          "Interior Design",
          "International Agriculture",
          "International Business",
          "International Relations",
          "International Studies",
          "Islamic Studies",
          "Italian",
          "Japanese",
          "Jazz Studies",
          "Jewelry and Metalsmithing",
          "Jewish Studies",
          "Journalism",
          "Kinesiology",
          "Korean",
          "Land Use Planning and Management",
          "Landscape Architecture",
          "Landscape Horticulture",
          "Latin American Studies",
          "Library Science",
          "Linguistics",
          "Logistics Management",
          "Management Information Systems",
          "Managerial Economics",
          "Marine Biology Major",
          "Marine Science",
          "Marketing Major",
          "Mass Communication",
          "Massage Therapy",
          "Materials Science",
          "Mathematics",
          "Mechanical Engineering",
          "Medical Technology",
          "Medieval and Renaissance Studies",
          "Mental Health Services",
          "Merchandising and Buying Operations",
          "Metallurgical Engineering",
          "Microbiology",
          "Middle Eastern Studies",
          "Military Science",
          "Mineral Engineering",
          "Missions",
          "Modern Greek",
          "Molecular Biology",
          "Molecular Genetics",
          "Mortuary Science",
          "Museum Studies",
          "Music",
          "Music Education",
          "Music History Major",
          "Music Management",
          "Music Therapy",
          "Musical Theater",
          "Native American Studies",
          "Natural Resources Conservation",
          "Naval Architecture",
          "Neurobiology",
          "Neuroscience",
          "Nuclear Engineering",
          "Nursing Major",
          "Nutrition",
          "Occupational Therapy",
          "Ocean Engineering",
          "Oceanography",
          "Operations Management",
          "Organizational Behavior Studies",
          "Painting",
          "Paleontology",
          "Pastoral Studies",
          "Peace Studies",
          "Petroleum Engineering",
          "Pharmacology",
          "Pharmacy",
          "Philosophy",
          "Photography",
          "Photojournalism Major",
          "Physical Education",
          "Physical Therapy",
          "Physician Assistant",
          "Physics",
          "Physiological Psychology",
          "Piano",
          "Planetary Science",
          "Plant Pathology",
          "Playwriting and Screenwriting",
          "Political Communication",
          "Political Science Major",
          "Portuguese",
          "Pre-Dentistry",
          "Pre-Law",
          "Pre-Medicine",
          "Pre-Optometry",
          "Pre-Seminary",
          "Pre-Veterinary Medicine",
          "Printmaking",
          "Psychology",
          "Public Administration",
          "Public Health",
          "Public Policy Analysis",
          "Public Relations Major",
          "Radio and Television",
          "Radiologic Technology",
          "Range Science and Management",
          "Real Estate",
          "Recording Arts Technology",
          "Recreation Management",
          "Rehabilitation Services",
          "Religious Studies",
          "Respiratory Therapy",
          "Risk Management",
          "Rural Sociology",
          "Russian",
          "Scandinavian Studies",
          "Sculpture",
          "Slavic Languages and Literatures",
          "Social Psychology",
          "Social Work",
          "Sociology",
          "Soil Science",
          "Sound Engineering",
          "South Asian Studies",
          "Southeast Asia Studies",
          "Spanish Major",
          "Special Education",
          "Speech Pathology",
          "Sport and Leisure Studies",
          "Sports Management",
          "Statistics Major",
          "Surveying",
          "Sustainable Resource Management",
          "Teacher Education",
          "Teaching English as a Second Language",
          "Technical Writing",
          "Technology Education",
          "Textile Engineering",
          "Theatre",
          "Theology",
          "Tourism",
          "Toxicology",
          "Turfgrass Science",
          "Urban Planning",
          "Urban Studies",
          "Visual Communication",
          "Voice",
          "Web Design",
          "Webmaster and Web Management",
          "Welding Engineering",
          "Wildlife Management",
          "Women's Studies",
          "Youth Ministries",
          "Zoology",
        ],
      },
    ],
  ],

  // Step 7
  [
    [
      { text: "Will this be your first time attending CruzHacks?" },
      { inputType: "combo", field: "first_cruzhacks", options: ["Yes", "No"] },
    ],
    [
      { text: "Have you attended any hackathons before? If so, how many?" },
      {
        inputType: "combo",
        field: "hackathon_experience",
        options: ["Yes", "No"],
      },
    ],
    [
      { text: "Do you have prior tech experience?" },
      { inputType: "textarea", field: "tech_experience", showCount: false },
    ],
  ],

  // Step 8
  [
    [
      { text: "Which of the following best describes you?" },
      // TODO: allow multiple choices
      {
        inputType: "radio",
        field: "ethnic_background",
        options: [
          "Asian Indian",
          "Black/African",
          "Chinese",
          "Filipino",
          "Korean",
          "Guamanian/Chamorro",
          "Japanese",
          "Hispanic/Lation/Spanish Origin",
          "Middle Eastern",
          "Vietnamese",
          "Native Hawaiian",
          "Samoan",
          "Native American or Alaskan Native",
          "White",
          "Other Pacific Islander",
          "Other Asian (Cambodian, Thai, etc.)",
          "No Answer",
        ],
        other: true,
        arrange: "vertical-inline",
      },
    ],
  ],

  // Step 9
  // TODO : multiple selections
  [
    [
      { text: "Pronouns" },
      { text: "Select all that apply", type: "subtitle" },
      {
        inputType: "radio",
        field: "pronouns",
        options: [
          "She/Her/Hers",
          "He/Him/His",
          "They/Them/Theirs",
          "any",
          "Prefer not to answer",
        ],
        other: true,
      },
    ],
  ],

  // Step 10
  [
    [
      { text: "What is your gender identy?" },
      { text: "Select as many as you'd like", type: "subtitle" },
      // TODO: multiple selections
      {
        inputType: "radio",
        field: "gender",
        options: [
          "Man",
          "Woman",
          "Non-Binary",
          "Cisgender",
          "Transgender",
          "Prefer not to answer",
        ],
        other: true,
      },
    ],
  ],

  // Step 11
  [
    [
      { text: "Do you consider yourself any of the following?" },
      {
        inputType: "radio",
        field: "sexual_orientation",
        options: [
          "Heterosexual or straight",
          "Gay or lesbian",
          "Bisexual",
          "Queer",
          "Prefer Not to Answer",
        ],
        other: true,
      },
    ],
  ],

  // Step 12
  [
    [
      {
        text: "Do you identify as part of an underrepresented group in the technology industry?",
      },
      {
        inputType: "radio",
        field: "underepresented_group",
        options: ["Yes", "No"],
      },
    ],
  ],
]
