name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    env:
      VITE_FIREBASE_API_KEY: "${{ secrets.API_KEY }}"
      VITE_FIREBASE_AUTH_DOMAIN: "${{ secrets.AUTH_DOMAIN }}"
      VITE_FIREBASE_DATBASE_URL: "${{ secrets.DATABASE_URL }}"
      VITE_FIREBASE_PROJECT_ID: "${{ secrets.PROJECT_ID }}"
      VITE_FIREBASE_STORAGE_BUCKET: "${{ secrets.STORAGE_BUCKET }}"
      VITE_FIREBASE_MESSAGING_SENDER_ID: "${{ secrets.MESSAGING_SENDER_ID }}"
      VITE_FIREBASE_APP_ID: "${{ secrets.APP_ID }}"
      VITE_FIREBASE_MEASUREMENT_ID: "${{ secrets.MEASUREMENT_ID }}"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Create Production Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: development
          path: build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint

  deploy_development:
    needs: [build, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: development
          path: build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: development
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CRUZHACKS_2024_DEVELOPME_D58C3 }}"
          channelId: live
          projectId: cruzhacks-2024-developme-d58c3
